### ISSUE TITLE
Native fault when running the app

### ISSUE THREAD

**Issue by nisrulz** [gvsumasl/EchoprintForAndroid#12]
Here is what is working for me
- I have fixed the app and I can build it in Android Studio. 
- I see codegen generating the hash

But the app crashes..
- Initial suspect was Memory leak , but when i tested it with leak canary nothing came up .
- Next I looked through  the app logs and saw it was crashing via some native function under libc causing a fault 

`A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10 in tid 3555 (edu.gvsu.masl)`

Can you explain me why this would occur.

One more anomaly I could see was 

![screen shot 2016-02-09 at 7 17 02 pm](https://cloud.githubusercontent.com/assets/2096087/12917847/c6b34fbe-cf61-11e5-9fec-b69ac27d2af7.jpeg)

But the app compiles well without any error and I can deploy it on the device.

Any help regarding this would be helpful.

**Comment by alexrestrepo** [comment]
If you changed the package name/path you may need to re-create the header file and signature for the native codegen function (using javah).
